CC = gcc
CFLAGS = -Wall -Wextra -std=c99 -pedantic
TARGET = simarm
OBJS = simarm.o

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

simarm.o: simarm.c
	$(CC) $(CFLAGS) -c simarm.c

clean:
	rm -f $(TARGET) $(OBJS)